-- Generated by tools/package_mod.py; regenerate after source edits.
return {
    version = "3.1.0-dev",
    sourceHash = "c66e8b9184df43a06f636a54a01c80fbda95f38fc05c71cd272855c9108f154f",
    baseCommit = "32ab565349fef707fcd5e4f1c3cf1002a65225ec",
    animationHash = "c4738fecb8c571b0f5c81d39df7f49e392b38579420e6d6839b52247e7708d9a",
    workingTree = "development",
    schemaVersion = 2,
}
