-- Generated by tools/package_mod.py; regenerate after source edits.
return {
    version = "3.1.0-dev",
    sourceHash = "037a12b3dc81bd42a6b51a4e05b016ebe8a57c51cd1a18e8cb0d8bcd4b1282ab",
    baseCommit = "bf5c518620400547468518aa794eae556724aedc",
    animationHash = "c4738fecb8c571b0f5c81d39df7f49e392b38579420e6d6839b52247e7708d9a",
    workingTree = "development",
    schemaVersion = 2,
}
