-- Generated by tools/package_mod.py; regenerate after source edits.
return {
    version = "3.1.0-dev",
    sourceHash = "5dad1d4718467348d94fcd0670312508d1fbd66af8644105d6dbd702ad7d78de",
    baseCommit = "cecdfb0767733549b672425037689bf6cfdb342e",
    animationHash = "c4738fecb8c571b0f5c81d39df7f49e392b38579420e6d6839b52247e7708d9a",
    workingTree = "development",
    schemaVersion = 2,
}
