"""Generate reproducible source metadata and a local installable mod ZIP (no publishing)."""
import argparse
import hashlib
import json
import subprocess
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNTIME = ('config', 'control', 'data', 'decision', 'entities', 'recording', 'render', 'sensors', 'threat', 'utils')

def runtime_files():
    files = [ROOT/'main.lua', ROOT/'metadata.xml']
    for folder in RUNTIME:
        files.extend(p for p in (ROOT/folder).glob('*.lua') if p != ROOT/'config/build.lua')
    return sorted(files)

def metadata():
    digest = hashlib.sha256()
    for path in runtime_files():
        digest.update(path.relative_to(ROOT).as_posix().encode())
        digest.update(b'\0')
        digest.update(path.read_bytes())
    return {'version': '3.1.0-dev', 'sourceHash': digest.hexdigest(),
            'baseCommit': subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True).strip(),
            'animationHash': hashlib.sha256((ROOT/'data/npc_animdb.lua').read_bytes()).hexdigest(),
            'workingTree': 'development', 'schemaVersion': 2}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    meta = metadata()
    lines = ['-- Generated by tools/package_mod.py; regenerate after source edits.', 'return {']
    for key, value in meta.items():
        lines.append(f'    {key} = {json.dumps(value, ensure_ascii=False)},')
    lines.append('}')
    build = ROOT/'config/build.lua'
    build.write_text('\n'.join(lines)+'\n', encoding='utf-8')
    files = runtime_files()+[build, ROOT/'IMPLEMENTATION.md']
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(args.output, 'w', zipfile.ZIP_DEFLATED) as archive:
        for path in files:
            info = zipfile.ZipInfo('ghoststep3/'+path.relative_to(ROOT).as_posix(), date_time=(2026, 9, 8, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, path.read_bytes())
    print(json.dumps({'zip': str(args.output.resolve()), **meta}, ensure_ascii=False, indent=2))

if __name__ == '__main__':
    main()
